#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${CYAN}[dev]${NC} $*"; }
warn() { echo -e "${YELLOW}[dev]${NC} $*"; }
err()  { echo -e "${RED}[dev]${NC} $*" >&2; }

cleanup() {
  log "Shutting down..."

  # Send SIGTERM first for graceful shutdown
  for pid_var in FRONTEND_PID BACKEND_PID; do
    local pid="${!pid_var:-}"
    [[ -z "$pid" ]] && continue
    if kill -0 "$pid" 2>/dev/null; then
      kill -TERM "$pid" 2>/dev/null
      log "Sent SIGTERM to $pid_var ($pid)"
    fi
  done

  # Wait up to 5s for processes to exit gracefully
  local deadline=$((SECONDS + 5))
  for pid_var in FRONTEND_PID BACKEND_PID; do
    local pid="${!pid_var:-}"
    [[ -z "$pid" ]] && continue
    while kill -0 "$pid" 2>/dev/null && (( SECONDS < deadline )); do
      sleep 0.2
    done
    # Force kill if still alive
    if kill -0 "$pid" 2>/dev/null; then
      kill -9 "$pid" 2>/dev/null
      warn "Force killed $pid_var ($pid)"
    fi
  done

  wait 2>/dev/null

  # Clean up any stragglers on our ports
  for port in "${BACKEND_PORT:-8080}" "${FRONTEND_PORT:-3000}"; do
    local remaining
    remaining=$(lsof -ti "tcp:$port" 2>/dev/null || true)
    if [[ -n "$remaining" ]]; then
      warn "Port $port still occupied — cleaning up PID(s): $remaining"
      echo "$remaining" | xargs kill -9 2>/dev/null || true
    fi
  done

  log "Done."
}
trap cleanup EXIT INT TERM

# ── Preflight checks ────────────────────────────────────────

if ! command -v go &>/dev/null; then
  err "Go is not installed. Install it from https://go.dev/dl/"
  exit 1
fi

if ! command -v node &>/dev/null; then
  err "Node.js is not installed."
  exit 1
fi

# ── Free occupied ports ─────────────────────────────────────

BACKEND_PORT=8080
FRONTEND_PORT=3000

free_port() {
  local port=$1
  local pids
  pids=$(lsof -ti "tcp:$port" 2>/dev/null || true)
  if [[ -n "$pids" ]]; then
    warn "Port $port is occupied by PID(s): $pids — killing..."
    echo "$pids" | xargs kill -9 2>/dev/null || true
    sleep 0.5
    # verify
    if lsof -ti "tcp:$port" &>/dev/null; then
      err "Failed to free port $port"
      exit 1
    fi
    log "Port $port freed"
  fi
}

free_port "$BACKEND_PORT"
free_port "$FRONTEND_PORT"

# ── Backend .env check ──────────────────────────────────────

if [[ ! -f "$BACKEND_DIR/.env" ]]; then
  err "backend/.env not found. Copy from .env.example and fill in values:"
  err "  cp backend/.env.example backend/.env"
  exit 1
fi

# ── Frontend .env (auto-generate if missing) ────────────────

if [[ ! -f "$FRONTEND_DIR/.env" ]]; then
  warn "frontend/.env not found — generating with local backend defaults..."
  cat > "$FRONTEND_DIR/.env" <<'EOF'
# Auto-generated by scripts/dev.sh
AI_TOPICS_DATA_SOURCE=mock
AI_TOPICS_API_BASE_URL=http://localhost:8080

OPENCLAW_OFFICE_DATA_SOURCE=live
OPENCLAW_AGENT_STATUS_URL=http://localhost:8080/v1/agents/status
OPENCLAW_GATEWAY_LATEST_STATUS_URL=http://localhost:8080/v1/gateway/status/latest
OPENCLAW_GATEWAY_STATUS_URL=http://localhost:8080/v1/gateway/status

NEXT_PUBLIC_WS_URL=ws://localhost:8080/v1/ws
EOF
  log "Created frontend/.env"
fi

# ── Install dependencies if needed ─────────────────────────

if [[ ! -d "$FRONTEND_DIR/node_modules" ]]; then
  log "Installing frontend dependencies..."
  (cd "$FRONTEND_DIR" && npm install)
fi

log "Downloading backend modules..."
(cd "$BACKEND_DIR" && go mod download)

# ── Start backend ───────────────────────────────────────────

log "Starting backend on :$BACKEND_PORT ..."
(cd "$BACKEND_DIR" && go run ./cmd/server) &
BACKEND_PID=$!

# Wait for backend to be ready
for i in $(seq 1 30); do
  if curl -sf http://localhost:8080/healthz >/dev/null 2>&1; then
    log "${GREEN}Backend ready${NC}"
    break
  fi
  if ! kill -0 "$BACKEND_PID" 2>/dev/null; then
    err "Backend process exited unexpectedly"
    exit 1
  fi
  sleep 1
done

# ── Start frontend ──────────────────────────────────────────

log "Starting frontend on :$FRONTEND_PORT ..."
(cd "$FRONTEND_DIR" && npm run dev) &
FRONTEND_PID=$!

sleep 2

echo ""
log "═══════════════════════════════════════════════════"
log "  Frontend : ${GREEN}http://localhost:3000${NC}"
log "  Office   : ${GREEN}http://localhost:3000/office${NC}"
log "  Backend  : ${GREEN}http://localhost:8080${NC}"
log "  Health   : ${GREEN}http://localhost:8080/healthz${NC}"
log "  Gateway  : ${GREEN}http://localhost:8080/v1/gateway/status${NC}"
log "═══════════════════════════════════════════════════"
log "Press ${YELLOW}Ctrl+C${NC} to stop all services"
echo ""

wait
